### ISSUE TITLE
fix?

### ISSUE THREAD

**Issue by NinjaMoon** [hicolour/env#5]
Hello after the base can not be used normally .xinitrc
Dunst&
_/ .dzen / status_checks / checker.sh&
Will cause the desktop card owner to comment out the problem disappearing,
However, the MOD+W button function does not work properly

**Comment by hicolour** [comment]
Hey @NinjaMoon, give me a day I need to test it on clear enviroment.

The main issue is that you cannot launch X desktop ?

**Comment by NinjaMoon** [comment]
感谢您发布配置，我很喜欢，但是运行后会有一些问题

1.
git clone https://github.com/hicolour/env.git
make base
reboot
startx
可以启动x，但是xmonad不能使用，会卡主

2.
修改 .xinitrc 
#Dunst＆
#_ / .dzen / status_checks / checker.sh＆
可以正常使用

但是
mod+w
mod+shhift+q
输入后没有任何反应，不能使用

    [ ("M-w"                    , addName "Switch to Project"           $ switchProjectPrompt warmPromptTheme)
    , ("M-S-w"                  , addName "Shift to Project"            $ shiftToProjectPrompt warmPromptTheme)
  , ("M-S-q"                  , addName "Quit XMonad"                     $ confirmPrompt hotPromptTheme "Quit XMonad" $ io (exitWith ExitSuccess))

**Comment by NinjaMoon** [comment]
Thank you for publishing the configuration, I like it, but there will be some problems after running

1.
Git clone https://github.com/hicolour/env.git
Base
Reboot
Run startx
Can start X, but xmonad can not be used, will card owners

2.
Modify .xinitrc
#Dunst &
#_ / .dzen / status_checks / checker.sh&
Can be used normally

but
MOD+ W
MOD+ shhift+ Q
No response after input, can not be used

[("M-w", addName "switch to project" $ switchProjectPrompt warmPromptTheme)
, ("M-S-w", addName "Shift to Project" $ shiftToProjectPrompt warmPromptTheme)
, ("M-S-q", addName "Quit XMonad" $ confirmPrompt hotPromptTheme "Quit XMonad" $ io (exitWith ExitSuccess))

**Comment by NinjaMoon** [comment]
Hello, are you still online?

**Comment by hicolour** [comment]
please do `git pull origin master` I just removed two chckers that mioght cause your issues

**Comment by hicolour** [comment]
Project commands and xmonad quit doesn't work, I'm working on the fix

**Comment by NinjaMoon** [comment]
Thanks for the fix, continue to wait for your project command and xmonad exit doesn't work fix

**Comment by NinjaMoon** [comment]
.xinitrc ~/.personal/env-screen.sh does not have this file, dzen2 will blacken if the right mouse button is clicked, and dzen will often switch between the card and the host.
myWorkspaces = [wsGEN,wsPRIV,wsWRK1,wsWRK2,wsIDE,wsSLACK,wsSKYPE,wsTMP]
Do not show.

**Comment by NinjaMoon** [comment]
I retry this project
Git Clone https://github.com/hicolour/env.git
basis
Reboot
Run startx
All problems are still there,

**Comment by hicolour** [comment]
In case of .personal this is example project 

https://github.com/hicolour/.personal-exmaple/blob/master/README.md

but it should work without that

**Comment by NinjaMoon** [comment]
Do you still have the time to fix the error? If you don't fix it, I might try xmonad for other projects.

**Comment by NinjaMoon** [comment]
可以再在主题添加一个新的功能吗？
http://hackage.haskell.org/package/xmonad-contrib-0.13/docs/XMonad-Actions-GridSelect.html

**Comment by NinjaMoon** [comment]
Can you add a new feature to the theme again?
http://hackage.haskell.org/package/xmonad-contrib-0.13/docs/XMonad-Actions-GridSelect.html

**Comment by hicolour** [comment]
I just added Vagrantfile, `make base` is working properly
